package com.jamiltonquintero.solid.o.casoUno;

public enum InformeEnum {
    CUENTA_CREDITO,
    CUENTA_AHORROS,

    CUENTA_AHORROS_EMPESA,
    CUENTA_AHORROS_EMPESA_PEQUNA,
    CUENTA_AHORROS_EMPESA_MEDIANA,
    CUENTA_AHORROS_EMPESA_MULTINACIONAL,
    X

}
